class EstateListData {
  String id;
  String imageUrl;
  String titleTxt;
  String subTxt;
  double distance;
  double rating;
  int reviews;
  int perMonth;
  String description;
  String lordLandName;
  String lordLandImage;

  EstateListData({
    this.imageUrl = '',
    this.titleTxt = '',
    this.subTxt = '',
    this.distance = 1.8,
    this.reviews = 83,
    this.rating = 4.5,
    this.perMonth = 270,
    this.description = _description,
    this.lordLandName = '',
    this.lordLandImage = '',
    this.id = '',
  });

  static List<EstateListData> estateList = <EstateListData>[
    EstateListData(
      imageUrl: 'assets/images/estate_1.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 71,
      rating: 4.4,
      perMonth: 165,
      lordLandName: 'Joan Li',
      lordLandImage: 'assets/images/Joan.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_2.jpg',
      titleTxt: 'Beverly House',
      subTxt: 'Kensington, London',
      distance: 4,
      reviews: 94,
      rating: 4.5,
      perMonth: 200,
      lordLandName: 'Jada Wiraputra',
      lordLandImage: 'assets/images/Jada.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/hotel_5.jpg',
      titleTxt: 'Duplex apartment',
      subTxt: 'Kensington, NY',
      distance: 3,
      reviews: 62,
      rating: 4.8,
      perMonth: 265,
      lordLandName: 'Michelle Elis',
      lordLandImage: 'assets/images/Elis.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/hotel_3.jpg',
      titleTxt: 'King House',
      subTxt: 'Kensington, London',
      distance: 7,
      reviews: 107,
      rating: 4.4,
      perMonth: 190,
      lordLandName: 'Allan Omotocho',
      lordLandImage: 'assets/images/Allan.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/hotel_4.jpg',
      titleTxt: 'Royal Sea Crown',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 240,
      rating: 4.5,
      perMonth: 200,
      lordLandName: 'Choice Lamas',
      lordLandImage: 'assets/images/Choice.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_6.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 71,
      rating: 4.4,
      perMonth: 165,
      lordLandName: 'Joan Li',
      lordLandImage: 'assets/images/Joan.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_7.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 71,
      rating: 4.4,
      perMonth: 165,
      lordLandName: 'Stefania Liam',
      lordLandImage: 'assets/images/Stefania.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_8.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 71,
      rating: 4.4,
      perMonth: 165,
      lordLandName: 'Albert Dera',
      lordLandImage: 'assets/images/Albertdera.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_9.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 71,
      rating: 4.4,
      perMonth: 165,
      lordLandName: 'Joanna Nix',
      lordLandImage: 'assets/images/joanna-nix.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_10.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 71,
      rating: 4.4,
      perMonth: 165,
      lordLandName: 'Christina Wocintech',
      lordLandImage: 'assets/images/christina-wocintech.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_11.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 71,
      rating: 4.4,
      perMonth: 165,
      lordLandName: 'Vince Fleming',
      lordLandImage: 'assets/images/vince-fleming.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_12.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 71,
      rating: 4.4,
      perMonth: 165,
      lordLandName: 'Milan Cisneros',
      lordLandImage: 'assets/images/Milan-cisneros.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_13.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 71,
      rating: 4.4,
      perMonth: 165,
      lordLandName: 'Ben Parker',
      lordLandImage: 'assets/images/ben-parker.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_14.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 71,
      rating: 4.4,
      perMonth: 165,
      lordLandName: 'Elizeu Dias',
      lordLandImage: 'assets/images/elizeu-dias.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_15.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 3,
      reviews: 84,
      rating: 4.8,
      perMonth: 265,
      lordLandName: 'Ali Morshedlou',
      lordLandImage: 'assets/images/ali-morshedlou.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_16.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 71,
      rating: 4.4,
      perMonth: 165,
      lordLandName: 'Gregory Hayes',
      lordLandImage: 'assets/images/gregory-hayes.jpg',
    ),
    EstateListData(
      imageUrl: 'assets/images/estate_17.jpg',
      titleTxt: 'Grand Royal ',
      subTxt: 'Kensington, NY',
      distance: 2,
      reviews: 71,
      rating: 4.4,
      perMonth: 165,
      lordLandName: 'Jurica Koletic',
      lordLandImage: 'assets/images/jurica-koletic.jpg',
    ),
  ];
}

const _description =
    'Lorem ipsum is simply dummy text of printing & typesetting industry, Lorem ipsum is simply dummy text of printing and typesetting industry,Lorem ipsum is simply dummy text of printing and typesetting industry.';
